litellm_settings:
  set_verbose: True
  cache: True
  drop_params: True
  success_callback: ["langfuse"]

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  store_model_in_db: True
  store_prompts_in_spend_logs: True
